// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorloniPoint.API.Data;

#nullable disable

namespace TorloniPoint.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TorloniPoint.API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Turma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RA")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("TorloniPoint.API.Models.FormularioDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BoaConvivencia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CarteirasOrganizadas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Colaboracao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Materiais")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Organizacao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Participacao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Patrimonio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespeitoColegas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespeitoCombinados")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespeitoProfessores")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SalaLimpa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SemCelular")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FormulariosDiarios");
                });

            modelBuilder.Entity("TorloniPoint.API.Models.RegistroEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("RegistrosEntrada");
                });

            modelBuilder.Entity("TorloniPoint.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Turma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TorloniPoint.API.Models.RegistroEntrada", b =>
                {
                    b.HasOne("TorloniPoint.API.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });
#pragma warning restore 612, 618
        }
    }
}
